language: node_js
node_js:
  - "8"

cache: npm

after_success:
  - npm run coverage

services:
  - postgresql

addons:
  postgresql: "9.6"


before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
