language: node_js
node_js:
  - "8"

cache: npm

after_success:
  - npm run coverage

services:
  - postgresql

addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
